### PR TITLE
[Feat] support secure url in Helius constructor

### PR DESCRIPTION
**Pull request by kAsky53**
Breaking changes:

* changed Helius.apiKey as optional.
* changed constructor parameter with optional object `HeliusConfig`.

### CODE REVIEW

**Comment by kAsky53** [comment]
This is PR for #86.
@0xIchigo need your review. Thanks!

**Comment by 0xIchigo** [comment]
Thank you for the PR! We've been discussing this internally, and unfortunately, we don't really have the cycles to take care of breaking changes at the moment. I'm going to leave this PR open so that we can discuss it more in the future

**Comment by kAsky53** [comment]
> Thank you for the PR! We've been discussing this internally, and unfortunately, we don't really have the cycles to take care of breaking changes at the moment. I'm going to leave this PR open so that we can discuss it more in the future

@0xIchigo would it be approved if I make it a fully backward compatible by any chance?

**Comment by kAsky53** [comment]
@0xIchigo it should be fully backward compatible as of now. Thanks!

**Review by 0xIchigo — APPROVED** [review]
Thank you for your contribution! LGTM 🔥

**Pull request merged**
