### PR TITLE
fix(txts): `sendSmartTransaction` Times Out But Transaction Is Confirmed

### LINKED ISSUE #102: Transactions goes through but sendSmartTransaction returns timeout error
Had sendSmartTransaction function return `Transaction failed to confirm in 60s` even though the transaction was confirmed, (_causing the user to make a new one not knowing the first one went through_), it just throws that error it doesn't return any tx id so I can't check confirmation status in the code.

### PR DESCRIPTION
**Pull request by tavindev**
Fixes #102 by throwing timeout error only if the current block height is greater than the `lastValidBlockHeight` returned by `getLatestBlockhash` used when creating the transaction.

### CODE REVIEW

**Review by 0xIchigo — COMMENTED** [review]
Thank you for the PR — it was in my backlog, so this is very based! 

The only issue that I'm trying to work through with this PR is on line 663 where the condition of the `while` loop is changed to `((await this.connection.getBlockHeight()) <= lastValidBlockHeight)`. This means that for every iteration of the loop, we're making an async RPC call. We want to try to optimize for speed here, which is why I'm hesitant to merge this straight away. Maybe we could add this in after the 60s timeout? Like we break out of the loop, check if the blockhash is still valid, and then go from there? That way we only introduce slowness near the end for transactions that haven't been confirmed yet, and are almost about to expire, instead of every transaction

**Comment by tavindev** [comment]
Thanks for the follow up!

Good point. We could use `while (Date.now() - startTime < timeout || (await this.connection.getBlockHeight()) <= lastValidBlockHeight)` instead, which would then only check the blockhash after the `timeout`. Considering that a transaction times out after ~60-90s, `getBlockHeight` would be called at most ~2 times. This way, only transactions near expiry time would have extra RPC calls. What do you think?

**Comment by 0xIchigo** [comment]
No worries @tavindev! Yeah, that OR condition would work a lot better since we still have the initial timeout. I'm all for it

**Comment by tavindev** [comment]
Done!

**Review by 0xIchigo — CHANGES_REQUESTED** [review]
Very nice! Only nit is that we should change the return type for `createSmartTransaction` to `Promise<{ smartTransaction: Transaction | VersionedTransaction, lastValidBlockHeight: number }>`. And then the doc comments would be: `@returns {Promise<{ smartTransaction: Transaction | VersionedTransaction, lastValidBlockHeight: number }>} - The transaction and the last valid block height`

**Review by 0xIchigo — CHANGES_REQUESTED** [review]
Very based! Would you be able to update the Jito Smart Transactions (i.e., `createSmartTransactionWithTip` and `sendSmartTransactionWithTip`) accordingly so they reflect these new changes? Other than that, LGTM 🔥

**Review by 0xIchigo — APPROVED** [review]
Extremely based. Thank you for your contribution! 🔥

**Pull request merged**
